# schedule
from datetime_func import *

class BaseVal:
    RUN_SCHEDULE = None # RUN_SCHEDULE = {순번 : [파일명, (나가는 월들), 나가는일자, 수행날짜와 원천의 차이]
    EX_KEY_DICT = None
    FINAL_FILE_NAME_DICT = None
    str_d = None
    last_day = None

    def __init__(self, str_d):
        self.str_d = str_d  # yyyymm
        self.last_day = return_last_day_of_yyyymm(str_d[:4],str_d[4:])
        EVERY_MONTH = (1,2,3,4,5,6,7,8,9,10,11,12)

        # RUN_SCHEDULE = {순번 : [파일명, (나가는 월들), 나가는일자, 수행날짜와 원천의 차이]
        RUN_SCHEDULE = {
                        "1"    :["리얼탑KB아파트단지매핑",EVERY_MONTH, "25", None],
                        "2"    :["리얼탑 kb아파트평형시세매핑(sas)",EVERY_MONTH,"25", None],
                        "4"    :["건축물신축단가관리(excel)",(1,),"말일", None, None],
                        "5"    :["산단격차율",EVERY_MONTH,"5", 2,],
                        "6"    :["토지격차율(sas)",(1,8),"말일", None],
                        "8"    :["전국주택 매매가격지수",EVERY_MONTH,"20",1],
                        "9"    :["오피스텔 매매가격지수",EVERY_MONTH,"20",1],
                        "10"   :["용도지역별 지가지수",EVERY_MONTH,"말일",1],
                        "11"   :["리얼탑토지특성정보",(0,),None,"?",0], #공개 후 1개월 이내
                        "32"   :["이용상황별 지가변동률",EVERY_MONTH,"20",2],
                        "33-51":["공동주택 통합 매매실거래가격지수 ~ 연립 다세대 매매 평균가격",EVERY_MONTH,"20",3], # 37은 제외, 아래에 있음
                        "37"   :["아파트 매매 실거래가격지수_시군구분기별",(1,4,7,10),"20",None],
                        "52"   :["경기종합지수(2020=100) (10차)",EVERY_MONTH,"20",2],
                        "53"   :["품목별 소비자물가지수(품목성질별: 2020=100)",EVERY_MONTH,"20",1],
                        "54"   :["생산자물가지수(품목별)(2020=100)",EVERY_MONTH,"20",2],
                        "55"   :["면적별 건축물 현황",(6,),"말일",None],
                        "56"   :["용도별 건축물 현황",(6,),"말일",None],
                        "57"   :["층수별 건축물 현황",(6,),"말일",None],
                        "58"   :["동수별 연면적별 건축착공현황",EVERY_MONTH,"말일",2],
                        "59"   :["동수별 연면적별 건축허가현황",EVERY_MONTH,"말일",2],
                        "60"   :["시도별 건축물착공현황",EVERY_MONTH,"말일",2],
                        "61"   :["연도별 건축허가현황",(7,),"말일",None],
                        "62"   :["시도별 재건축사업 현황 누계",(7,),"말일",None],
                        "63"   :["(新)주택보급률",(4,),"20",None],
                        "64"   :["주택 멸실현황",(3,),"말일",None],
                        "65"   :["부문별 주택건설 인허가실적(월별누계)",EVERY_MONTH,"말일",2],
                        "66"   :["주택건설실적총괄",(3,),"20",None],
                        "67"   :["주택규모별 주택건설 인허가실적(월별누계)",EVERY_MONTH,"말일",2],
                        "68"   :["지역별 주택건설 인허가실적",(3,),"20",None],
                        "69"   :["공사완료후 미분양현황",EVERY_MONTH,"20",3],
                        "70"   :["규모별 미분양현황",EVERY_MONTH,"말일",2],
                        "71"   :["미분양현황종합",(2,),"20",None,None],
                        "72"   :["시군구별 미분양현황",EVERY_MONTH,"말일",2],
                        "73"   :["공동주택현황",EVERY_MONTH,"20",2,None],
                        "74"   :["주택유형별 주택준공실적_ 다가구구분",EVERY_MONTH,"말일",2],
                        "75"   :["주택유형별 착공실적_다가구 구분,월계",EVERY_MONTH,"말일",2],
                        "76-80":["부동산시장 소비심리지수~주택전세시장 소비심리지수",EVERY_MONTH,"말일",1],
                        "81"   :["국토부 상가수익률",(2,5,8,11),"말일",None],
                        "82"   :["K-REMAP지수",EVERY_MONTH,"말일",2],
                        "83"   :["전국산업단지현황통계",(3,6,9,12),"말일",None],
                        "84"   :["국가산업단지산업동향",EVERY_MONTH,"말일",2],
                        "85"   :["팩토리온 등록공장현황",EVERY_MONTH,"말일",2],
                        "86"   :["이용상황별 지가지수",EVERY_MONTH,"20",2],
                        "87"   :["주요정책사업(혁신도시) 지가지수",EVERY_MONTH,"20",2],
                        "88"   :["예금취급기관의 가계대출[주택담보대출+기타대출] 지역별(월별)",EVERY_MONTH,"20",3],
        }
        self.RUN_SCHEDULE = RUN_SCHEDULE

        FINAL_FILE_NAME_DICT = {
                        "1"    :None,
                        "2"    :None,
                        "4"    :None,
                        "5"    :None,
                        "6"    :None,
                        "8"    :None,
                        "9"    :None,
                        "10"   :f"rtp_landpi_inf_{self.str_d}.txt",
                        "11"   :None, #공개 후 1개월 이내
                        "32"   :None,
                        "33"   :None,
                        "34"   :None,
                        "35"   :None,
                        "36"   :None,
                        "37"   :None,
                        "38"   :None,
                        "39"   :None,
                        "40"   :None,
                        "41"   :None,
                        "42"   :None,
                        "43"   :None,
                        "44"   :None,
                        "45"   :None,
                        "46"   :None,
                        "47"   :None,
                        "48"   :None,
                        "49"   :None,
                        "50"   :None,
                        "51"   :None,
                        "52"   :None,
                        "53"   :None,
                        "54"   :None,
                        "55"   :f"24.rtp_sqr_con_{self.str_d}{self.last_day}.txt",
                        "56"   :f"25.rtp_yongdo_con_{self.str_d}{self.last_day}.txt",
                        "57"   :f"26.rtp_floor_con_{self.str_d}{self.last_day}.txt",
                        "58"   :f"27.rtp_d_alsqr_st_{self.str_d}{self.last_day}.txt",
                        "59"   :f"28.rtp_d_alsqr_pm_{self.str_d}{self.last_day}.txt",
                        "60"   :f"29.rtp_sido_st_{self.str_d}{self.last_day}.txt",
                        "61"   :None,
                        "62"   :None,
                        "63"   :None,
                        "64"   :None,
                        "65"   :f"34.rtp_field_hse_pm_m_{self.str_d}{self.last_day}.txt",
                        "66"   :None,
                        "67"   :f"36.rtp_hse_sz_pm_{self.str_d}{self.last_day}.txt",
                        "68"   :None,
                        "69"   :None,
                        "70"   :f"39.rtp_sz_us_{self.str_d}{self.last_day}.txt",
                        "71"   :None,
                        "72"   :f"41.rtp_sigungu_us_{self.str_d}{self.last_day}.txt",
                        "73"   :None,
                        "74"   :f"43.rtp_hse_ut_m_{self.str_d}{self.last_day}.txt",
                        "75"   :f"44.rtp_hse_st_m_{self.str_d}{self.last_day}.txt",
                        "76"   :f"45.rtp_re_csi_inf_{self.str_d}{self.last_day}.txt",
                        "77"   :f"46.rtp_hse_csi_inf_{self.str_d}{self.last_day}.txt",
                        "78"   :f"47.rtp_ld_csi_inf_{self.str_d}{self.last_day}.txt",
                        "79"   :f"48.rtp_hse_t_csi_inf_{self.str_d}{self.last_day}.txt",
                        "80"   :f"49.rtp_hse_js_csi_inf_{self.str_d}{self.last_day}.txt",
                        "81"   :None,
                        "82"   :f"51.rtp_k_remap_{self.str_d}{self.last_day}.txt",
                        "83"   :f"52.ked_sandan_st_{self.str_d}{self.last_day}.txt",
                        "84"   :f"53.ked_sandan_in_{self.str_d}{self.last_day}.txt",
                        "85"   :f"54.ked_fac_on_stt_{self.str_d}{self.last_day}.txt",
                        "86"   :None,
                        "87"   :None,
                        "88"   :None,
        }
        self.FINAL_FILE_NAME_DICT = FINAL_FILE_NAME_DICT

        # 외부통계 key 컬럼 인덱스 번호
        EX_KEY_DICT = {
            "32":[0,1,4],
            "33":[0,1,5],
            "34":[0,1,5],
            "35":[0,1,3,6],
            "36":[0,1,3,6],
            "37":[0,1,4], # 실제데이터받고 한번더확인
            "38":[0,1,5],
            "39":[0,1,4],
            "40":[0,1,3,6],
            "41":[0,1,3,6],
            "42":[0,1,4],
            "43":[0,1,4],
            "44":[0,1,4],
            "45":[0,1,4],
            "46":[0,1,4],
            "47":[0,1,4],
            "48":[0,1,4],
            "49":[0,1,4],
            "50":[0,1,4],
            "51":[0,1,4],
            "52":[0,31],
            "53":[0,1,3,8],
            "54":[0,1,5],
            "55":[0,1,3,7],
            "56":[0,1,3,7],
            "57":[0,1,3,7],
            "58":[0,1,2,6],
            "59":[0,1,2,6],
            "60":[0,1,3,5,6,9,11,14],
            "61":[0,1,5], # 실제데이터받고 한번더확인
            "62":[0, 1, 3, 4, 8], # 실제데이터받고 한번더확인
            "63":[0, 1, 3, 6], # 실제데이터받고 한번더확인
            "64":[0, 1, 3, 6], # 실제데이터 받고 한번더 확인
            "65":[0,1,3,6],
            "66":[0, 1, 4],
            "67":[0,1,3,6],
            "68":[0,1,4],
            "69":[0,1,3,6],
            "70":[0,1,3,6],
            "71":[0,1,4],
            "72":[0,1,4],
            "73":[0,1,3,6],
            "74":[0,1,3,6],
            "75":[0,1,3,6],
            "76":[0,1,4],
            "77":[0,1,4],
            "78":[0,1,4],
            "79":[0,1,4],
            "80":[0,1,4],
            "81":[0,1,2,18],
            "82":[0,1,4],
            "83":[0,1],
            "84":[0,1,2],
            "85":[0,1,2],
            "86":[0,1,3,6],
            "87":[0,1,4],
            "88":[0,1,3,6]
        }
        self.EX_KEY_DICT = EX_KEY_DICT